# Generated by Django 5.1.7 on 2026-04-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
