# Generated by Django 5.1.7 on 2026-04-29 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="actions_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="usage_period_started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
