# Generated by Django 5.1.7 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_subscription_usage_tracking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="usage_period_started_at",
            new_name="current_period_start",
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
