# Generated by Codex on 2026-05-19

from django.db import migrations


def _rename_legacy_summaries_used_column(apps, schema_editor):
    table_name = "api_subscription"
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        columns = {
            column.name
            for column in connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }

    if "summaries_used" in columns and "actions_used" not in columns:
        schema_editor.execute(
            f'ALTER TABLE "{table_name}" RENAME COLUMN "summaries_used" TO "actions_used"'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_user_username"),
    ]

    operations = [
        migrations.RunPython(
            _rename_legacy_summaries_used_column,
            migrations.RunPython.noop,
        ),
    ]

