# Generated by Django 6.0.5 on 2026-05-31 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_billing_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingcheckoutsession',
            new_name='api_pending_user_id_fd969d_idx',
            old_name='api_pending_user_id_5f25cc_idx',
        ),
    ]
