services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      # This tells Python to use the system-wide certificate store
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    expose:
      - "8000"
    container_name: backend
    restart: always
    env_file: ./backend/.env.production
    # Use Gunicorn instead of runserver for AWS
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1', 8000)); s.close()"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
    networks:
      - app_network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./nginx/certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
