services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      # This tells Python to use the system-wide certificate store
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # This maps your local folder to the container's /app folder
    container_name: backend
    restart: always
    env_file: ./backend/.env.dev
    # dev file uses runserver - development mode
    command: python manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1', 8000)); s.close()"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - ./backend/.env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
    postgres_data:

