services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      # This tells Python to use the system-wide certificate store
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # This maps your local folder to the container's /app folder
    container_name: backend
    restart: always
    env_file: ./backend/.env
    # dev file uses runserver - development mode
    command: python manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1', 8000)); s.close()"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
    networks:
      - app_network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
