FROM python:3.12-slim

# Set environment variables (prevents Python from buffering output)
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Update the package list and install the CA certificates package
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    update-ca-certificates


RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi"]