"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False),
    DJANGO_ENV=(str, "dev"),
)

django_env = env("DJANGO_ENV").lower() # type: ignore

env_file = BASE_DIR / (".env.prod" if django_env == "prod" else ".env.dev")
load_dotenv(env_file, override=True)

# environ.Env.read_env(os.path.join(BASE_DIR, '../.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False) # type: ignore
IS_PRODUCTION = not DEBUG
STRICT_SECURITY_VALIDATION = env.bool("STRICT_SECURITY_VALIDATION", default=IS_PRODUCTION) # type: ignore

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", default="") # type: ignore
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-key"
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG is False.")

ADMIN_URL_PATH = env.str("ADMIN_URL_PATH", default="admin/") # type: ignore

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["127.0.0.1", "localhost"] if DEBUG else [] # type: ignore
)
if IS_PRODUCTION and STRICT_SECURITY_VALIDATION:
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured("ALLOWED_HOSTS must be configured when DEBUG is False.")
    if "*" in ALLOWED_HOSTS: # type: ignore
        raise ImproperlyConfigured("ALLOWED_HOSTS cannot contain '*' when DEBUG is False.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

]

AUTH_USER_MODEL = 'api.User'

# allauth config for custom User model
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username", "password1*", "password2*"]
SOCIALACCOUNT_LOGIN_ON_GET = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'backend.middleware.NoIndexPrivatePagesMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'backend.urls'
LOGIN_REDIRECT_URL = env.str("LOGIN_REDIRECT_URL", default="/api/auth/social/jwt") # type: ignore
LOGOUT_REDIRECT_URL = env.str("LOGOUT_REDIRECT_URL", default="/api/") # type: ignore
SOCIAL_AUTH_SUCCESS_REDIRECT_URL = env.str("SOCIAL_AUTH_SUCCESS_REDIRECT_URL", default="/api/auth/social/complete") # type: ignore

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("POSTGRES_DB"),
        "USER": env.str("POSTGRES_USER"),
        "PASSWORD": env.str("POSTGRES_PASSWORD"),
        "HOST": env.str("POSTGRES_HOST"),
        "PORT": env.str("POSTGRES_PORT"),
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {"": {"handlers": ["console"], "level": "DEBUG" if DEBUG else "INFO"}},
}

TRUST_X_FORWARDED_PROTO = env.bool("TRUST_X_FORWARDED_PROTO", default=False) # type: ignore
# Only trust X-Forwarded-Proto when running behind a trusted proxy that strips
# incoming spoofed forwarded headers and sets this value itself.
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https") if TRUST_X_FORWARDED_PROTO else None
)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=IS_PRODUCTION) # type: ignore
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = env.str("SECURE_REFERRER_POLICY", default="same-origin") # type: ignore
SECURE_CROSS_ORIGIN_OPENER_POLICY = env.str("SECURE_CROSS_ORIGIN_OPENER_POLICY", default="same-origin") # type: ignore

_hsts_default_seconds = 31536000 if IS_PRODUCTION else 0
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=_hsts_default_seconds) # type: ignore
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False) # type: ignore
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False) # type: ignore

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EXT_IDS = env.list("EXT_ID", default=[]) # type: ignore
_cors_allowed_origins = env.list("CORS_ALLOWED_ORIGINS", default=[]) # type: ignore
for _ext_id in EXT_IDS:
    _cors_allowed_origins.append(f"chrome-extension://{_ext_id}")
CORS_ALLOWED_ORIGINS = list(dict.fromkeys(_cors_allowed_origins)) # type: ignore
CORS_ALLOW_CREDENTIALS = True

_csrf_trusted_origins = env.list("CSRF_TRUSTED_ORIGINS", default=[]) # type: ignore
for _ext_id in EXT_IDS:
    _csrf_trusted_origins.append(f"chrome-extension://{_ext_id}")
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(_csrf_trusted_origins)) # type: ignore
if IS_PRODUCTION and STRICT_SECURITY_VALIDATION:
    if not CORS_ALLOWED_ORIGINS:
        raise ImproperlyConfigured(
            "CORS_ALLOWED_ORIGINS must be set when DEBUG is False and credentials are enabled."
        )
    if not CSRF_TRUSTED_ORIGINS:
        raise ImproperlyConfigured("CSRF_TRUSTED_ORIGINS must be set when DEBUG is False.")

ANON_THROTTLE_SUMMARIES_COUNT = env.int("THROTTLE_SUMMARIES_COUNT", default=1) # type: ignore
ANON_THROTTLE_SUMMARIES_PERIOD = env.str("THROTTLE_SUMMARIES_PERIOD", default="day").lower() # type: ignore
if ANON_THROTTLE_SUMMARIES_PERIOD not in {"sec", "min", "hour", "day", "month"}:
    ANON_THROTTLE_SUMMARIES_PERIOD = "day"

PDF_MAX_UPLOAD_SIZE_BYTES = env.int("PDF_MAX_UPLOAD_SIZE_BYTES", default=10 * 1024 * 1024) # type: ignore

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'api.exception_handlers.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': f'{ANON_THROTTLE_SUMMARIES_COUNT}/{ANON_THROTTLE_SUMMARIES_PERIOD}',
        'auth': '3/sec',
        'me': '20/min',
    },
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.CookieJWTAuthentication',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    'AUTH_COOKIE': 'access_token',  # Cookie name. Enables cookies if value is set.
    "AUTH_REFRESH_COOKIE": 'refresh_token',
    'AUTH_COOKIE_DOMAIN': None,     # A string like "example.com", or None for standard domain cookie.
    'AUTH_COOKIE_SECURE': env.bool("AUTH_COOKIE_SECURE", default=IS_PRODUCTION),    # Whether the auth cookies should be secure (https:// only). # type: ignore
    'AUTH_COOKIE_HTTP_ONLY' : True, # Http only cookie flag.It's not fetch by javascript.
    'AUTH_COOKIE_PATH': '/',        # The path of the auth cookie.
    'AUTH_REFRESH_COOKIE_PATH': '/api/token/refresh', # Narrow refresh-token cookie scope.
    'AUTH_COOKIE_SAMESITE': 'None',  # Whether to set the flag restricting cookie leaks on cross-site requests.
}

if IS_PRODUCTION and SIMPLE_JWT["AUTH_COOKIE_SAMESITE"] == "None" and not SIMPLE_JWT["AUTH_COOKIE_SECURE"]:
    raise ImproperlyConfigured(
        "AUTH_COOKIE_SECURE must be True when AUTH_COOKIE_SAMESITE is 'None' in production."
    )

# CSRF Permissions
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=IS_PRODUCTION) # type: ignore
_csrf_samesite_default = "None" if IS_PRODUCTION else "Lax"
CSRF_COOKIE_SAMESITE = env.str("CSRF_COOKIE_SAMESITE", default=_csrf_samesite_default) # type: ignore
if CSRF_COOKIE_SAMESITE == "None" and not CSRF_COOKIE_SECURE:
    raise ImproperlyConfigured(
        "CSRF_COOKIE_SECURE must be True when CSRF_COOKIE_SAMESITE is 'None'."
    )

# Django session/CSRF cookie hardening for production HTTPS deployments.
SESSION_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = env.str("SESSION_COOKIE_SAMESITE", default="Lax") # type: ignore


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'prompt': 'select_account',
        },
        'APP': {
            'client_id': env.str("GOOGLE_CLIENT_ID"),
            'secret': env.str("GOOGLE_CLIENT_SECRET"),
            'key': ''
        }
    }
}
